### ISSUE TITLE
[BUG] Your issue here...

### ISSUE THREAD

**Issue by gharb0129** [oblivioncth/OFILb#1]
When I launch an Adobe flash game from Launchbox it will not work and gives me an error:

_CLI Flashpoint
Could not start F:\Emulators\Adobe Flash Player\Flashpoint 8.2 Infinity\FPSoftware\Redirector\Redirect.exe!

Execution will now be aborted._

I've attached an image of the error.

If I open Flashpoint and then launch the same game from flashpoint the game works fine.
After I open the game in Flashpoint, I can then go back to launchbox and launch the game from launchbox and it works fine.

It seems like this issue only occurs if:

1. Restart your computer (act like you booted up your PC for the very first time)
2. Flashpoint is closed.
3. Launchbox is closed
4. Open Launchbox
5. Launch an adobe flash game from launchbox that has been imported with the importer tool. This error only seems to occur with games that utilize the Adobe flash player (not Shockwave or any of the other flash tools)
6. See error

**Expected behavior**
The game should open in launchbox without having to open flashpoint first.

**Screenshots**
![image](https://user-images.githubusercontent.com/67556798/102919334-a91c1c00-4456-11eb-83bb-339d8f16f64c.png)

**Version (please complete the following information):**
- OFILb version - 0.1.1.0
- CLIFp version - 0.3.1.0
- Flashpoint version - 8.2

**Additional context**

**Comment by oblivioncth** [comment]
Hi,

My apologizes, I managed to miss this when you first submitted it and I'm sorry you are having this issue.

The code base has changed significantly since version 0.1.1.0 and it is possible that the issue you are experiencing has been fixed since then. Additionally, this is actually a problem with CLIFp, the program that OFILb deploys that actually lets you run Flashpoint games. I know this isn't exactly apparent if you're just trying to use this for LaunchBox so no worries, but in general for the future:

- Issues while running the import tool: OFILb issue
- Issues while trying to run a game/animation: CLIFp issue

If it isn't too much of an inconvenience I ask that you try using the latest version of OFILb (v0.3, which also comes with the latest CLIFp) and see if you still have the issue.  If you do, open an issue in the tracker for CLIFp https://github.com/oblivioncth/CLIFp/issues

You can more or less copy and paste this one if it's exactly the same.
